name: better_repo_annotation
description: A new Flutter package. Works for iOS, Android, Linux, Web, MacOS and Windows apps. Describe initial release. Repository class code generation.
version: 0.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0
